language: scala

scala:
  - "2.11.6"

jdk:
  - oraclejdk8

env:
  - CASSANDRA_VERSION=3.0.13 SPARK_VERSION=2.1.1 SPARK_PACKAGE_TYPE=hadoop2.7
  - CASSANDRA_VERSION=2.2.9  SPARK_VERSION=2.1.1 SPARK_PACKAGE_TYPE=hadoop2.7
  - CASSANDRA_VERSION=2.1.17 SPARK_VERSION=2.1.1 SPARK_PACKAGE_TYPE=hadoop2.7
  - CASSANDRA_VERSION=3.0.13 SPARK_VERSION=2.0.2 SPARK_PACKAGE_TYPE=hadoop2.7
  - CASSANDRA_VERSION=2.2.9  SPARK_VERSION=2.0.2 SPARK_PACKAGE_TYPE=hadoop2.7
  - CASSANDRA_VERSION=2.1.17 SPARK_VERSION=2.0.2 SPARK_PACKAGE_TYPE=hadoop2.7

addons:
  apt:
    packages:
    - build-essential
    - python-dev
    - python-pip
    - python-tox
    - python-virtualenv
    - libev4
    - libev-dev
  
script: JVM_OPTS= make clean lint dist start-cassandra test-travis stop-cassandra

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
    - $HOME/.sbt
    - $HOME/.local
    - $HOME/.cache/pip

